NREL/alfalfa

- client/boptest.py
* The tags have writeStatus not writeVal in the inputs.
* `start_one` needs to read the kwargs, not the `sim_params`
> Input writeVal to writeStatus and use kwargs for start_one

- .pre-commit-config.yaml
- alfalfa_worker/__main__.py
- alfalfa_worker/lib/precheck_argus.py
- alfalfa_worker/step_sim/step_fmu.py
- alfalfa_worker/worker.py
The previous code migration seemed to break the FMU running. These changes address running the FMU on the worker node. 
Caveats:
* The start time is always 0 (or the beginning of the FMU year)
* I changed the order of the step_fmu.py arguments to be the same as the step_osm arguments.
> Fix running FMUs with Alfalfs

- alfalfa_worker/add_site/add_site.py
- alfalfa_worker/step_sim/osm_model_advancer.py
> Fix issue with osw jobs that have schedule:externalfile

- alfalfa_worker/requirements/production.txt
> Add python libs

- .github/workflows/ci.yml
- alfalfa_worker/requirements/test.txt
> Time out each integration test if if doesn't complete within 2 minuutes.

- worker/steposm/mlep/mlep_process.py
- Update implemented for cbi lab branch
> update MlepProcess.read() method to stop read on newline

- docker-compose-historian.yml
> lockdown influxdb @ 1.8

- alfalfa_worker/Dockerfile
Include spawn executable in PATH.
Closes #147
> Download and install Spawn.

- .env
- CHANGELOG.md
- deploy/README.md
- deploy/k8s-historian.yml
Feedback welcome on our initial version number and the CHANGELOG structure.  I imagine that for future releases we'll include issues and PRs for the date range.
I've tested the published develop images and the [deployment directions](https://github.com/NREL/alfalfa/wiki/Deployment) with docker-compose and on the Rancher Kubernetes environment. Ready to release!
Closes #165
> Release docs

- alfalfa_web/server/advancer.js
> Increase advance timeout to 1 minute

- alfalfa_web/Dockerfile
- alfalfa_web/server/dbops.js
- deploy/build_web.sh
> move dbops.js out of generic lib folder

- alfalfa_web/Dockerfile
- alfalfa_worker/step_sim/osm_model_advancer.py
Hotfix #242.  I'm developing integrations against the released version (0.1.0) rather than develop.
> Give E+ a minute to warm up.

- alfalfa_worker/Dockerfile
> Update install commands for Spawn

- alfalfa_worker/Dockerfile
- pyproject.toml
Merge main back into develop and resolve conflicts (mainly from Spawn install in main).
> Main into develop

- alfalfa_web/components/StartDialog/StartDialog.js
- alfalfa_web/package-lock.json
- alfalfa_web/package.json
Luxon had to be downgraded to v1 to satisfy material-ui-pickers v3 requirements
> Fixed datetime picker

- alfalfa_worker/worker_openstudio/osm_model_advancer.py
We're intermittently hitting timeout errors during warmup.
> 3 min timeout for warm up

- alfalfa_worker/Dockerfile
- alfalfa_worker/jobs/modelica/step_run.py
- alfalfa_worker/lib/data/data_generator.py
This is a simple update to pull in the data_generator.py file from BOPTEST's repo. The Dockerfile and step_run update are small changes not related to the pull from BOPTEST.
> pull in latest FMU-related libraries from boptest

- alfalfa_worker/lib/job.py
- alfalfa_worker/lib/run.py
- tests/worker/jobs/empty_job_1.py
- tests/worker/jobs/empty_job_2.py
- tests/worker/test_run.py
@nllong this should fix the `run.job_history` issues you've been having
> Fix job_history recording

- alfalfa_worker/jobs/openstudio/step_run.py
- tests/integration/test_refrig_case_osw.py
> Add fix for incorrect timesteps when days roll over

- .github/workflows/ci.yml
- docker-compose.dev.yml
- docker-compose.yml
According to this issue https://github.com/docker/compose/issues/3722 adding `container_name` to a service is "antithetical to scaling"
> Remove worker container_name

- poetry.lock
- pyproject.toml
I think this fixes it?
Addresses #375
> Fix Failing Tests

- alfalfa_web/server/resolvers.js
- alfalfa_worker/jobs/modelica/step_run.py
- alfalfa_worker/jobs/openstudio/step_run.py
- alfalfa_worker/lib/job.py
- alfalfa_worker/lib/models.py
- alfalfa_worker/lib/run.py
- alfalfa_worker/lib/run_manager.py
- tests/worker/helpers/mock_mongo_data.py
> Move sim_time to redis

- alfalfa_worker/jobs/openstudio/step_run.py
Were getting a weird bug with getting null packets from mlep. This PR fixes this by extending the timeout and adding an exception in case e+ times out.
> Extend timeout for e+ simulation to start and remove workaround

- .github/workflows/ci.yml
get rid of action step in favor of built in behavior
> Merge Fix Publish Job (#432) into main

- alfalfa_worker/Dockerfile
- alfalfa_worker/jobs/openstudio/lib/workflow/measures/alfalfa_python_environment/measure.rb
- tests/integration/models/refrig_case_osw/in.idf
- tests/integration/models/refrig_case_osw/measures/prep_idf/measure.rb
- tests/integration/models/small_office/measures/python_ems/measure.rb
> Update to openstudio 3.6.1 and energyplus 23.1.0

- docker-compose.yml
> Bump mongo to version 6

- alfalfa_worker/jobs/openstudio/lib/alfalfa-lib-gem/lib/alfalfa_mixin.rb
> Add import of json in ruby mixin to prevent crashes
