.github/workflows/ci.yml, alfalfa_worker/requirements/production.txt, alfalfa_worker/requirements/test.txt, alfalfa_worker/step_sim/osm_model_advancer.py, tests/integration/test_rtu_coodination_osw.py, tests/integration/test_simple_fmu_control.py, tests/integration/test_single_zone_vav_fmu.py, tests/integration/test_small_office_osm.py
Use GitHub Actions instead of Travis since Travis is no longer reliably free for NREL projects (limited free builds shared across organization).
I also removed the pysindy dependency which is necessary for one user but not broadly applicable.
Fixes #82.
=> Gh actions

alfalfa_worker/worker.py
Before this change, the presence of realtime or timescale options in the
job payload would cause the external clock option to be ignored. This
change gives external clock more priority. If external clock is present
then other options are not used.
close #117
=> Fix broken external clock option

alfalfa_web/Dockerfile, alfalfa_worker/Dockerfile
* Newer versions of poetry cause this build script to break, locking version for now.
* Need to force install node
=> lock version of poetry and force install nodejs

alfalfa_worker/Dockerfile-test
This file wasn't used anymore and the worker/tests/test.py doesn't exist.
=> remove unused Dockerfile-test

poetry.lock, pyproject.toml
Purposefully holding back redis, numpy, pandas. The latter two need newer python which needs to happen too.
`importlib-metadata` will need to be updated in conjunction with `alfalfa-client`, so holding off on that.
see other inline comments.
@TShapinsky  -- can you test this locally before merging? I blew away and created a new virtualenv to test these updates.
Fixes #213
=> upgrade dependencies

alfalfa_worker/worker_openstudio/osm_model_advancer.py
Larger models need more time for EnergyPlus to go through startup/warmup.
1 minute is arbitrary but probably enough for most models.
close #242
=> Increase timeout for mlep to 1 min

LICENSE.md, alfalfa_web/app.js, alfalfa_web/components/App/App.js, alfalfa_web/components/Sims/Sims.js, alfalfa_web/components/Sites/PointDialogComponent.js, alfalfa_web/components/Sites/Sites.js, alfalfa_web/components/StartDialog/StartDialog.js, alfalfa_web/components/Upload/AddJobMutation.js, alfalfa_web/components/Upload/Upload.js, alfalfa_web/scripts/post_sign.js, alfalfa_web/server/advancer.js, alfalfa_web/server/alfalfa-server.js, alfalfa_web/server/api-haystack.js, alfalfa_web/server/api-v2.js, alfalfa_web/server/dbops.js, alfalfa_web/server/index.js, alfalfa_web/server/resolvers.js, alfalfa_web/server/schema.js, alfalfa_web/test/economizer.js, alfalfa_web/webpack.config.js, alfalfa_worker/__main__.py, alfalfa_worker/dispatcher.py, alfalfa_worker/jobs/openstudio/annual_run.py, alfalfa_worker/jobs/openstudio/lib/merge_osws.rb, alfalfa_worker/jobs/openstudio/lib/parse_variables.py, alfalfa_worker/jobs/openstudio/lib/translate_osm.rb, alfalfa_worker/step_sim_utils.py
This PR removes individual license text in favor of the centralized `LICENSE.md` in the repo root.
- `alfalfa_worker/jobs/openstudio/lib/workflow/measures/*`
- `alfalfa_worker/jobs/openstudio/lib/workflow/openstudio-alfalfa-gem/*`
=> Centralized License

alfalfa_worker/lib/job.py, tests/worker/jobs/log_reader_job.py, tests/worker/test_run.py
- Added `self.checkin_run()` to error handling code.
- Added test which throws error and then confirms that error exists in `jobs.log` that was committed to the run
=> Check in run when error in job is experienced

alfalfa_worker/Dockerfile, alfalfa_worker/jobs/openstudio/create_run.py, alfalfa_worker/jobs/openstudio/lib/merge_osws.rb, alfalfa_worker/jobs/openstudio/lib/workflow/measures/python/measure.rb, alfalfa_worker/jobs/openstudio/lib/workflow/measures/python/measure.xml, alfalfa_worker/jobs/openstudio/lib/workflow/workflow.osw
Addresses #110 
When a OpenStudio run is created the job checks for any `requirements.txt` files. If any are found it creates a virtual environment in the run directory and installs packages. The E+ idf is then modified to point to that directory via its python path. This could and should be used by energy modelers to get their python dependencies into alfalfa. The main goal is to make it possible to add dependencies without having to create custom images and restarting the server.
The main downside (that I can see) from this change is that models which take advantage of this will have significantly larger than those without a virtual environment. This is because the entire environment is packaged with the run. One alternative would be to install packages worker wide, however, this would …
=> Python dependency management

alfalfa_web/server/api-v2.js, alfalfa_web/server/resolvers.js, alfalfa_worker/jobs/step_run_base.py
There have been some exceptions raised saving the messages with types other than strings. This enforces the data to pass as strings, then typed correctly on the other side.
=> Pass realtime, external_clock, and timescale as string

alfalfa_worker/jobs/openstudio/step_run.py
We were still writing to mongo for every output point for every step. This seems to provide a speed up in my limited testing of greater than 20 times. I can now run the refrig_test model at over 300x realtime on my machine when I couldn't run at more than 15x before.
I discovered this while working on PR #364
=> Small Optimization for Point Writing

alfalfa_worker/jobs/openstudio/create_run.py, alfalfa_worker/jobs/openstudio/lib/workflow/measures/alfalfa_python_environment/measure.rb, alfalfa_worker/jobs/openstudio/lib/workflow/measures/alfalfa_python_environment/measure.xml, alfalfa_worker/jobs/openstudio/lib/workflow/workflow.osw, alfalfa_worker/lib/job.py, tests/worker/jobs/subprocess_mock_job.py, tests/worker/test_job_subprocess_calls.py
the measure for adding python environment to the idf was called `python` this is a pretty common measure name for projects using python. If there are two measures with the same directory name things break very badly. So I'm changing the measure name to `alfalfa_python_environment`.
=> Change python measure name

tests/integration/models/small_office/measures/python_ems/resources/requirements.txt
Apparently installing from `sklearn` was EOLed two hours ago. This broke the python environment integration test. This should fix that by point to the new repo.
=> Move from sklearn to scikit-learn in test

alfalfa_worker/jobs/openstudio/lib/workflow/measures/alfalfa_site_sensors/measure.rb
Buildings which do not have natural gas equipment will error out if a sensor reading the natural gas meter is added.
In the future we could re add with some logic about when to add the natural gas meter.
=> Temporarily remove automatic natural gas metering

alfalfa_web/components/Sites/Sites.js, alfalfa_web/server/api.js
Right now alfalfa will not show a site until after it has been processed and information has been extracted from the model. In cases where the model is somehow broken this results in an error being generated but not relayed to the user. This PR removed the requirement of a site entry to be generated in the database. I'm open to critiques of this technique. I do believe that we have a lot of redundancy between Site and Run collections at this current point in time, but now doesn't seem like the time to reconcile that.
=> Report preprocessing errors and consolidate site information collection

.github/workflows/ci.yml, alfalfa_web/server/api.js, alfalfa_worker/jobs/openstudio/step_run.py, alfalfa_worker/lib/models.py, tests/integration/test_small_office_osw.py
This PR allows the user to stop controlling a point by setting it to `None` via the client
fixes #435
=> add ability to disable control points

alfalfa_web/components/Sims/Sims.js, alfalfa_web/components/Sites/Sites.js, alfalfa_web/server/api-v2.js, alfalfa_web/server/api.js
Adds the ability to download a ready, complete or errorred site from the UI.
- Adds `sites/:siteId/download` endpoint which redirects to a signed download url from minio
- Clicking the button opens a new tab to download the file. This allows multiple to be downloaded simultaneously (this does get intercepted by pop up blockers though)
Fixes #446
=> Add download site button

alfalfa_web/server/api.js
Ran into some issues in Lab where advance was timing out for a large, complex model. I believe this timeout was supposed to be 60 seconds originally but a 0 was missed. This PR corrects that.
=> Increase timeout for getting a reply from a run from 6 to 60 seconds

.github/workflows/ci.yml
All dependabot PRs are failing because they don't haver permissions to publish a new image to the container registry. This PR will remove that job when the actor running the action is dependabot
=> Check for dependabot before triggering publish action

alfalfa_worker/jobs/openstudio/lib/workflow/measures/alfalfa_metadata/measure.rb, alfalfa_worker/jobs/openstudio/lib/workflow/measures/alfalfa_metadata/measure.xml
This should have made it into an earlier PR.
It adds a measure which scrapes the Building object's name from the e+ idf and outputs it as a report. The intent is this measure can also be used in the future if we need to extract any other basic information about a model.
=> Scrape Building Name from EnergyPlus output

alfalfa_worker/jobs/openstudio/lib/alfalfa-lib-gem/lib/utils.rb, alfalfa_worker/jobs/openstudio/lib/workflow/measures/alfalfa_site_sensors/measure.rb
Add a program to divide site electricity sensor by 60 to convert it from Joules to Watts (Joules/Second).
=> Convert site electricity sensor from Joules to watts

.github/workflows/ci.yml
All the cool kids are getting rid of `latest` tags these days, but I realized that our deployment path is through them, so we should probably keep producing them for the near future.
=> Re-add pushing the latest tag upon release
